### ISSUE TITLE
Feature request: line numbers, triple backticks

### ISSUE THREAD

**Issue by DutchPete** [nothingislost/obsidian-codemirror-options#35]
I am still having to use a snippets for these:

```css
/* Line nos. in gutter */
/* smaller and less bright */
.theme-light
.cm-s-obsidian .CodeMirror-linenumber {
    opacity : 0;
    font-size: 10px !important;
}

/* Show line numbers only on hover */
.theme-dark
.cm-s-obsidian .CodeMirror-linenumber {
  opacity : 0;
}

.cm-s-obsidian .CodeMirror-linenumber:hover {
  opacity: 1;
}

/* align vertically with text */
.CodeMirror-gutter-wrapper { height:100%; }
.CodeMirror-gutter-elt { top:0; }
.cm-s-obsidian .CodeMirror-linenumber{ 
  height: 100%;
  line-height: 0;
}
.cm-s-obsidian .CodeMirror-linenumber::before {
  content: "";
  height: 50%;
  display: block;
}

/* align vertically with header */
.cm-s-obsidian .HyperMD-header {
  padding-top:0.125em;
  padding-bottom:0.125em;
}

/* align vertically with text in lists */
.cm-s-obsidian .HyperMD-list-line {
  padding-top:0.15em;
  padding-bottom:0.15em;
}
```

and also for these:

```css
/* Hide triple baclticks (```) for code block/Admonition */
div:not(.CodeMirror-activeline)>pre.HyperMD-codeblock.HyperMD-codeblock-end.CodeMirror-line,
div:not(.CodeMirror-activeline)>pre.HyperMD-codeblock.HyperMD-codeblock-begin.CodeMirror-line {
    background-color: transparent !important;
    display: inline !important;
    opacity: 0 !important;
}
```
